/*
  Общие блоки продукта, которые не тянут состояние (`@/state/useLibrary`, `@/state/usePremium`).
  Безопасно импортировать из общего индекса: в основной чанк они не попадают, только вместе со страницей.
  Блоки с состоянием (кнопки действий, `PostCard`, `AiTeaser`) — в `./actions` и лениво в `./lazy`.
*/
export { default as SectionHeader } from './SectionHeader/SectionHeader.vue'
export { default as HorizontalRail } from './HorizontalRail/HorizontalRail.vue'
export { default as RatingLabel } from './RatingLabel/RatingLabel.vue'
export { default as StatusBadge } from './StatusBadge/StatusBadge.vue'
export { default as PriceLabel } from './PriceLabel/PriceLabel.vue'
export { default as OpenNowLabel } from './OpenNowLabel/OpenNowLabel.vue'
export { default as ActionButton } from './ActionButton/ActionButton.vue'
export { default as ShareButton } from './ShareButton/ShareButton.vue'
export { default as PhotoAvatar } from './PhotoAvatar/PhotoAvatar.vue'
export { default as AuthorRow } from './AuthorRow/AuthorRow.vue'
export { default as AuthorCard } from './AuthorCard/AuthorCard.vue'
export { default as CommentItem } from './CommentItem/CommentItem.vue'
export { default as ReviewCard } from './ReviewCard/ReviewCard.vue'
export { default as DishRow } from './DishRow/DishRow.vue'
export { default as VenueCard } from './VenueCard/VenueCard.vue'
export { default as VenueRow } from './VenueRow/VenueRow.vue'
export { default as EventCard } from './EventCard/EventCard.vue'
export { default as EventRow } from './EventRow/EventRow.vue'
export { default as CollectionCard } from './CollectionCard/CollectionCard.vue'
export { default as CardSkeleton } from './CardSkeleton/CardSkeleton.vue'

export { FEATURE_LABELS, VENUE_POST_TOPIC_LABEL } from './labels'
export { SHARE_EVENT } from './ShareButton/types'
export { isRoutineEventStatus, isRoutineVenueStatus } from './StatusBadge/types'

export type { AuthorLike, HeadingLevel } from './shared/types'
export type { SectionHeaderProps } from './SectionHeader/types'
export type { HorizontalRailProps } from './HorizontalRail/types'
export type { RatingLabelProps } from './RatingLabel/types'
export type { StatusBadgeProps } from './StatusBadge/types'
export type { PriceLabelProps } from './PriceLabel/types'
export type { OpenNowLabelProps } from './OpenNowLabel/types'
export type { ActionButtonProps } from './ActionButton/types'
export type { ShareButtonProps, ShareKind, ShareTarget } from './ShareButton/types'
export type { PhotoAvatarProps } from './PhotoAvatar/types'
export type { AuthorRowProps } from './AuthorRow/types'
export type { AuthorCardProps } from './AuthorCard/types'
export type { CommentItemProps, CommentSendState } from './CommentItem/types'
export type { ReviewCardProps, ReviewVenueRef } from './ReviewCard/types'
export type { DishRowProps } from './DishRow/types'
export type { VenueCardProps } from './VenueCard/types'
export type { VenueRowProps } from './VenueRow/types'
export type { EventCardProps } from './EventCard/types'
export type { EventRowProps } from './EventRow/types'
export type { CollectionCardProps } from './CollectionCard/types'
export type { CardSkeletonKind, CardSkeletonProps } from './CardSkeleton/types'
